eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    web-application-type: reactive
  cloud:


    gateway:
      discovery:
        locator:
          enabled: true
      routes: # Ajoute tes routes ici
        - id: demandeMS
          uri: http://localhost:8090
          predicates:
              - Path=/credits/**
              - Path=/demandes/**
              - Path=/projects/**
              - Method=GET,POST,PUT,DELETE,OPTIONS

        - id: application1
          uri: http://localhost:8086
          predicates:
            - Path=/app1/get**

        - id: application2
          uri: http://localhost:8088
          predicates:
            - Path=/app2/get**

        - id: parametrageMS
          uri: http://localhost:8087
          predicates:
            - Path=/partners/** , /modalite/** , /conventions/** , /fonds/**






  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

  application:
    name : gateway-service

server:
  port: 8085



