keycloak-client:
  server-url: http://localhost:8080
  realm:  spring-micro-main

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs


  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
            AllowedHeaders:
              - Content-Type
      discovery:
        locator:
          enabled: true
      routes: # Ajoute tes routes ici
        - id: demandeMS
          uri: http://localhost:8091
          predicates:
              - Path=/credits/** , /demandes/** , /projects/**


              - Method=GET,POST,PUT,DELETE,OPTIONS

        - id: application1
          uri: http://localhost:8086
          predicates:
            - Path=/app1/get**

        - id: application2
          uri: http://localhost:8088
          predicates:
            - Path=/app2/get**

        - id: parametrageMS
          uri: http://localhost:8087
          predicates:
            - Path=/partners/** , /modalite/** , /conventions/** , /fonds/**
            - Method=GET,POST,PUT,DELETE,OPTIONS

        - id: users-service
          uri: http://localhost:8090
          predicates:
            - Path=/users/**





  logging:
    level:
      org.springframework.cloud.gateway: DEBUG

  application:
    name : gateway-service

server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: "*"


