#spring.application.name=eureka-service
#
#spring.config.import=configserver:http://localhost:8888

spring:
  application:
    name: eureka-service
  config:
    import: configserver:http://localhost:8888