

server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:

   active: native
  cloud:
   config:
     server:
       native:
         search-locations: file:///F:/workspaceSpring/stage/pfa/config-service/src/main/resources/configurations

