server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:

    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///F:/workspaceSpring/stage/pfa/config-service/src/main/resources/configurations


#server:
#  port: 8888
#
#spring:
#  application:
#    name: config-service
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file:///F:/workspaceSpring/stage/pfa/config-service/src/main/resources/configurations
#      discovery:
#        enabled: true
#
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVICE_URL:http://eureka-service:8761/eureka}
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include=*: